In [36]:
import torch

In [37]:
a = torch.Tensor([[0, 1], [2,3]])
a

tensor([[0., 1.],
        [2., 3.]])

In [38]:
# 根据下标进行索引
print(a[1])
print(a[0, 1])

tensor([2., 3.])
tensor(1.)


In [39]:
# 选择a中大于0的元素
a > 0

tensor([[False,  True],
        [ True,  True]])

In [40]:
# 选择符合条件的元素并返回
a[a>0]

tensor([1., 2., 3.])

In [41]:
# 选择非0的元素
torch.nonzero(a)

tensor([[0, 1],
        [1, 0],
        [1, 1]])

In [42]:
# torch.where(condition, x, y)
torch.where(a>1, torch.full_like(a, 1), a)

tensor([[0., 1.],
        [1., 1.]])

In [43]:
# 限制Tensor元素
a.clamp(1,2)

tensor([[1., 1.],
        [2., 2.]])

# 1 view()/resize()/reshape()

In [44]:
a = torch.arange(1, 5)
a

tensor([1, 2, 3, 4])

In [45]:
b = a.view(2, 2)
b

tensor([[1, 2],
        [3, 4]])

In [46]:
# non-inplace resize is deprecated
c = a.resize(4,1)
c

tensor([[1],
        [2],
        [3],
        [4]])

In [47]:
d = a.reshape(4,1)
d

tensor([[1],
        [2],
        [3],
        [4]])

In [48]:
b[0,0] = 0
c[1,0] = 0
d[2,0] = 0
a

tensor([0, 0, 0, 4])

In [49]:
a.resize_(2,3)
a, b, c, d

(tensor([[0, 0, 0],
         [4, 0, 0]]),
 tensor([[0, 0],
         [0, 4]]),
 tensor([[0],
         [0],
         [0],
         [4]]),
 tensor([[0],
         [0],
         [0],
         [4]]))

# 2 transpose()和permute()转置函数
* transpose()：将指定的两个维度进行转置
* permute()：按照给定的维度进行维度变换

In [50]:
a = torch.Tensor([[[1,2,3,4], [5,6,7,8], [9,10,11,12]], [[13,14,15,16], [17,18,19,20], [21,22,23,24]]])
a, a.shape, a.size()

(tensor([[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]],
 
         [[13., 14., 15., 16.],
          [17., 18., 19., 20.],
          [21., 22., 23., 24.]]]),
 torch.Size([2, 3, 4]),
 torch.Size([2, 3, 4]))

In [51]:
# 2,3,4 -> 3,2,4
a.transpose(0, 1)

tensor([[[ 1.,  2.,  3.,  4.],
         [13., 14., 15., 16.]],

        [[ 5.,  6.,  7.,  8.],
         [17., 18., 19., 20.]],

        [[ 9., 10., 11., 12.],
         [21., 22., 23., 24.]]])

In [52]:
# 2,3,4->4,3,2
a.permute(2,1,0)

tensor([[[ 1., 13.],
         [ 5., 17.],
         [ 9., 21.]],

        [[ 2., 14.],
         [ 6., 18.],
         [10., 22.]],

        [[ 3., 15.],
         [ 7., 19.],
         [11., 23.]],

        [[ 4., 16.],
         [ 8., 20.],
         [12., 24.]]])

# 3 squeeze()/unsqueeze()
- squeeze()：去掉size为1的维度
- unsqueeze()：将指定的维度size变为1

In [55]:
a = torch.Tensor([[1, 4]])
a.shape

torch.Size([1, 2])

In [56]:
a.unsqueeze(0).shape

torch.Size([1, 1, 2])

In [60]:
a = torch.randn(1,3,3, 1)
a.squeeze(0).shape

torch.Size([3, 3, 1])

In [61]:
a.squeeze().shape

torch.Size([3, 3])

# 4 expand()/expand_as()
- expand()：将Size为1的元素复制扩展到指定大小
- expand_as()：指定为Tensor的维度

In [62]:
a = torch.randn(2,2,1)
a

tensor([[[ 1.2661],
         [-2.3736]],

        [[-0.2682],
         [-0.7481]]])

In [ ]:
a.expand(2,2,3)